# Generated by Django 5.2.1 on 2025-07-21 00:56

from django.db import migrations
from pathlib import Path
import csv
import os


def import_section(apps, schema_editor):
    exported_data_path = Path(os.environ["WINE_LIST_DATA_DIR"])
    section_path = exported_data_path / "section.csv"

    Section = apps.get_model("wine_wiki", "Section")

    db_alias = schema_editor.connection.alias

    with open(section_path, "r") as f:
        csv_reader = csv.DictReader(f)

        sections = []
        for row in csv_reader:
            row["order"] = row.pop("section_order")
            sections.append(Section(**row))

        Section.objects.using(db_alias).bulk_create(sections)


def reverse_import_data(apps, schema_editor):
    Section = apps.get_model("wine_wiki", "Section")
    Section.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code=import_section, reverse_code=reverse_import_data)
    ]
