# Generated by Django 5.2.1 on 2025-07-21 00:56

from django.db import migrations
from pathlib import Path
import csv


def import_subsection(apps, schema_editor):
    exported_data_path = Path(
        "/Users/jonathan/jonathan/projects/wine_wiki/wine_list_db"
    )
    subsection_path = exported_data_path / "subsection.csv"

    SubSection = apps.get_model("wine_wiki", "SubSection")
    Section = apps.get_model("wine_wiki", "Section")

    db_alias = schema_editor.connection.alias

    with open(subsection_path, "r") as f:
        csv_reader = csv.DictReader(f)

        subsections = []
        for row in csv_reader:
            row["order"] = row.pop("subsection_order")
            section = Section.objects.get(section=row.pop("section"))

            subsections.append(SubSection(section=section, **row))

        SubSection.objects.using(db_alias).bulk_create(subsections)


def reverse_import_subsection(apps, schema_editor):
    SubSection = apps.get_model("wine_wiki", "SubSection")
    SubSection.objects.all().delete()

    pass


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0001_initial"),
        ("wine_wiki", "0002_populate_section"),
    ]

    operations = [
        migrations.RunPython(
            code=import_subsection, reverse_code=reverse_import_subsection
        )
    ]
