# Generated by Django 5.2.4 on 2025-08-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0005_subsubsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='All unstructured information about the wine. Supports Markdown formatting (see <a href=https://www.markdownguide.org/>guide</a>). Description is a 2nd level header field within the page, try to use third level and lower if including headers.', null=True),
        ),
    ]
