# Generated by Django 5.2.4 on 2025-08-05 07:14

import datetime
from django.db import migrations, models


def set_mod_date_eq_now(apps, schema_editor):
    now = datetime.datetime.now()
    formatted = now.strftime("%Y-%m-%d %H:%M:%S.%f")

    Wine = apps.get_model("wine_wiki", "Wine")

    wines = Wine.objects.all()

    for wine in wines:
        wine.modification_on = formatted
        wine.save()

    print(f"set modification_on to {formatted=}")


def set_mod_date_eq_create_date(apps, schema_editor):
    Wine = apps.get_model("wine_wiki", "Wine")

    wines = Wine.objects.all()

    for wine in wines:
        wine.modification_on = wine.created_on
        wine.save()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0006_alter_wine_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="modification_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            code=set_mod_date_eq_create_date,
            reverse_code=set_mod_date_eq_now,
        ),
        migrations.AlterField(
            model_name="wine",
            name="modification_on",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2025, 8, 5, 5, 10, 50, 174287, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
