# Generated by Django 5.2.4 on 2025-08-06 01:41

from django.db import migrations, models

id_author_map = {
    0: "Jonathan Stathakis",
    54: "Alison O'Brien",
    59: "Alison O'Brien",
    78: "Alison O'Brien",
    132: "Alison O'Brien",
    147: "Alison O'Brien",
    165: "Alison O'Brien",
    329: "Alison O'Brien",
    421: "Alison O'Brien",
    445: "Alison O'Brien",
    500: "Alison O'Brien",
    550: "Alison O'Brien",
    563: "Jonathan Stathakis",
    564: "Jonathan Stathakis",
    565: "Jonathan Stathakis",
    566: "Jonathan Stathakis",
}


def set_last_modification_by(apps, schema_editor):
    Wine = apps.get_model("wine_wiki", "Wine")

    for id, author in id_author_map.items():
        wine = Wine.objects.get(id=id)
        wine.last_modification_by = author
        wine.save()


def undo_last_modification_by(apps, sechema_editor):
    Wine = apps.get_model("wine_wiki", "Wine")

    for id in id_author_map:
        wine = Wine.objects.get(id=id)
        wine.last_modification_by = None
        wine.save()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0007_wine_modification_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="last_modification_by",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunPython(
            set_last_modification_by, reverse_code=undo_last_modification_by
        ),
    ]
