# Generated by Django 5.2.4 on 2025-08-07 23:37

from django.db import migrations, models


def populate_producer(apps, schema_editor):
    """
    Get the producer names from wine.producer and enter in producer.
    """

    Wine = apps.get_model("wine_wiki", "Wine")
    Producer = apps.get_model("wine_wiki", "Producer")

    wines = Wine.objects.all()

    # all producer names not null
    producer_names = (
        wines.filter(producer__isnull=False)
        .order_by()
        .values_list("producer", flat=True)
        .distinct()
    )

    if not producer_names:
        raise ValueError("No producer names found in wines")

    for name in list(producer_names):
        producer = Producer(name=name)
        producer.save()


def reverse_populate_producer(apps, schema_editor):
    Producer = apps.get_model("wine_wiki", "Producer")
    Producer.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0008_wine_last_modification_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Description of the producer"
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="region",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RenameField(
            model_name="producer",
            old_name="producer_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="producer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RunPython(
            code=populate_producer, reverse_code=reverse_populate_producer
        ),
    ]
