# Generated by Django 5.2.4 on 2025-08-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0008_wine_last_modification_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the producer'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
