# Generated by Django 5.2.4 on 2025-08-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0009_alter_producer_description_alter_producer_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='producer_name',
            new_name='name',
        ),
    ]
