# Generated by Django 5.2.4 on 2025-08-13 04:48

from django.db import migrations, models
from textwrap import dedent

update_wine_producer_id = dedent("""
update wine_wiki_wine
set producer_id = b.id
from (
select
    name as name,
    id as id
from
    wine_wiki_producer 
) as b
where
b.name = wine_wiki_wine.producer_name;
""")


reverse_update_wine_producer_id = dedent("""
update wine_wiki_wine
set producer_id = null;
""")


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0009_modify_fill_producer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wine",
            old_name="producer",
            new_name="producer_name",
        ),
        migrations.AddField(
            model_name="wine",
            name="producer_id",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.RunSQL(
            sql=update_wine_producer_id, reverse_sql=reverse_update_wine_producer_id
        ),
    ]
