# Generated by Django 5.2.4 on 2025-08-07 23:49

from django.db import migrations, transaction


def populate_producer(apps, schema_editor):
    """
    Get the producer names from wine.producer and enter in producer.
    """

    Wine = apps.get_model("wine_wiki", "Wine")
    Producer = apps.get_model("wine_wiki", "Producer")

    wines = Wine.objects.all()

    # all producer names not null
    producer_names = (
        wines.filter(producer__isnull=False)
        .order_by()
        .values_list("producer", flat=True)
        .distinct()
    )

    for name in list(producer_names):
        producer = Producer(name=name)
        producer.save()


def reverse_populate_producer(apps, schema_editor):
    Producer = apps.get_model("wine_wiki", "Producer")
    Producer.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0010_rename_producer_name_producer_name"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_producer, reverse_code=reverse_populate_producer
        )
    ]
