# Generated by Django 5.2.4 on 2025-08-13 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0010_insert_wine_producer_id"),
    ]

    operations = [
        migrations.RenameField("wine", "producer_id", "producer"),
        migrations.AlterField(
            model_name="wine",
            name="producer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="wine_wiki.producer",
            ),
        ),
    ]
