# Generated by Django 5.2.4 on 2025-08-13 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0011_alter_wine_producer_as_fk"),
    ]

    operations = [
        migrations.RunSQL(
            sql="alter table wine_wiki_wine drop column producer_name;",
            reverse_sql="alter table wine_wiki_wine add column producer_name varchar(100); update wine_wiki_wine set producer_name=name from wine_wiki_producer where wine_wiki_wine.producer_id = wine_wiki_producer.id",
            state_operations=[migrations.RemoveField("wine", "producer_name")],
        ),
    ]
