# Generated by Django 5.2.4 on 2025-08-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0011_populate_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
