# Generated by Django 5.2.4 on 2025-08-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0012_alter_producer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='producer',
            new_name='producer_name',
        ),
    ]
