# Generated by Django 5.2.4 on 2025-08-14 09:17

import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# wine_wiki.migrations.0014_populate_variety


def populate_variety(apps, schema_editor):
    Wine = apps.get_model("wine_wiki", "Wine")
    Variety = apps.get_model("wine_wiki", "Variety")

    varieties = list(
        Wine.objects.exclude(variety__isnull=True)
        .values_list("variety", flat=True)
        .distinct()
    )

    varieties.append("")  # cover cases where no variety present

    for name in varieties:
        variety = Variety(name=name)
        variety.save()


def reverse_populate_variety(apps, schema_editor):
    Variety = apps.get_model("wine_wiki", "Variety")

    Variety.objects.all().delete()


class Migration(migrations.Migration):
    replaces = [
        ("wine_wiki", "0013_variety"),
        ("wine_wiki", "0014_populate_variety"),
        ("wine_wiki", "0015_rename_variety_wine_variety_old_wine_variety_id"),
        ("wine_wiki", "0016_join_variety_wine_through_variety_id"),
        ("wine_wiki", "0017_alter_wine_variety"),
        ("wine_wiki", "0018_remove_wine_variety_old"),
    ]

    dependencies = [
        ("wine_wiki", "0012_remove_wine_producer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(
            code=populate_variety,
            reverse_code=reverse_populate_variety,
        ),
        migrations.RenameField(
            model_name="wine",
            old_name="variety",
            new_name="variety_old",
        ),
        migrations.AlterField(
            model_name="wine",
            name="variety_old",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wine",
            name="variety",
            field=models.CharField(default=""),
        ),
        migrations.RunSQL(
            sql="\nupdate\n    wine_wiki_wine\nset\n    variety = b.id\nfrom\n    wine_wiki_variety b\nwhere\n    wine_wiki_wine.variety_old = b.name\n",
            reverse_sql="\nupdate\n    wine_wiki_wine\nset\n    variety = ''\n",
        ),
        migrations.AlterField(
            model_name="wine",
            name="variety",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="wine_wiki.variety",
            ),
        ),
        migrations.RemoveField(
            model_name="wine",
            name="variety_old",
        ),
    ]
