# Generated by Django 5.2.4 on 2025-08-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0013_rename_producer_wine_producer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='producer_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
