# Generated by Django 5.2.4 on 2025-08-14 08:39

from django.db import migrations


def populate_variety(apps, schema_editor):
    Wine = apps.get_model("wine_wiki", "Wine")
    Variety = apps.get_model("wine_wiki", "Variety")

    varieties = list(
        Wine.objects.exclude(variety__isnull=True)
        .values_list("variety", flat=True)
        .distinct()
    )

    varieties.append("")  # cover cases where no variety present

    for name in varieties:
        variety = Variety(name=name)
        variety.save()


def reverse_populate_variety(apps, schema_editor):
    Variety = apps.get_model("wine_wiki", "Variety")

    Variety.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0013_variety"),
    ]

    operations = [
        migrations.RunPython(populate_variety, reverse_code=reverse_populate_variety)
    ]
