# Generated by Django 5.2.4 on 2025-08-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0014_populate_variety"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wine",
            old_name="variety",
            new_name="variety_old",
        ),
        migrations.AlterField(
            model_name="wine",
            name="variety_old",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wine",
            name="variety",
            field=models.CharField(default=""),
        ),
    ]
