# Generated by Django 5.2.4 on 2025-08-13 04:48

from django.db import migrations
from textwrap import dedent

update_wine_producer_id = dedent("""
update wine_wiki_wine
set producer_id = b.id
from (
select
    name as name,
    id as id
from
    wine_wiki_producer 
) as b
where
b.name = wine_wiki_wine.producer_name;
""")


reverse_update_wine_producer_id = dedent("""
update wine_wiki_wine
set producer_id = null;
""")


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0014_wine_producer_id"),
    ]

    operations = [
        migrations.RunSQL(
            sql=update_wine_producer_id, reverse_sql=reverse_update_wine_producer_id
        )
    ]
