# Generated by Django 5.2.4 on 2025-08-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0015_insert_wine_producer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='producer_id',
            new_name='producer',
        ),
    ]
