# Generated by Django 5.2.4 on 2025-08-14 08:56

from django.db import migrations
from textwrap import dedent

join_variety_wine = dedent(
    """
    update
        wine_wiki_wine
    set
        variety = b.id
    from
        wine_wiki_variety b
    where
        wine_wiki_wine.variety_old = b.name
    """
)

reverse_join_variety_wine = dedent(
    """
    update
        wine_wiki_wine
    set
        variety = ''
    """
)


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0015_rename_variety_wine_variety_old_wine_variety_id"),
    ]

    operations = [
        migrations.RunSQL(sql=join_variety_wine, reverse_sql=reverse_join_variety_wine)
    ]
