# Generated by Django 5.2.4 on 2025-08-14 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0016_join_variety_wine_through_variety_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='variety',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.variety'),
        ),
    ]
