# Generated by Django 5.2.4 on 2025-08-15 23:21

import django.db.models.deletion
from django.db import migrations, models
from textwrap import dedent


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0017_set_wine_variety_eq_variety_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="variety",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="wine_wiki.variety",
            ),
        ),
    ]
