# Generated by Django 5.2.4 on 2025-08-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0017_alter_wine_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='variety_old',
        ),
    ]
