# Generated by Django 5.2.4 on 2025-08-15 23:21

import django.db.models.deletion
from django.db import migrations, models
from textwrap import dedent


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0018_alter_wine_variety_set_as_fk"),
    ]

    operations = [
        migrations.RunSQL(
            sql=dedent(
                """
                alter table wine_wiki_wine drop column variety_old;
            """
            ),
            reverse_sql=dedent("""
            alter table wine_wiki_wine add column variety_old varchar default '';
            update wine_wiki_wine
            set
                variety_old = b.name
            from
                wine_wiki_variety as b
            where
                wine_wiki_wine.variety_id = b.id

"""),
        )
    ]
