# Generated by Django 5.2.4 on 2025-08-15 23:21

import django.db.models.deletion
from django.db import migrations, models
from textwrap import dedent


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0019_remove_wine_variety_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Description of the variety"
            ),
        ),
    ]
